### ISSUE TITLE
Output as a directed graph?

### ISSUE THREAD

**Issue by gausie** [CJex/regulex#40]
It might be an interesting idea to use this library to parse regex into a directed graph (perhaps using https://github.com/dagrejs/graphlib), and let other preexisting renderers produce the graphic (on the case of graphlib, https://github.com/dagrejs/dagre-d3 or https://github.com/dagrejs/dagre)

**Comment by CJex** [comment]
Transform regex syntax tree to some graph node types is very simple, I don't see the necessity  to builtin this function.
