### ISSUE TITLE
Error:Unexpected char!

### ISSUE THREAD

**Issue by DMKun** [CJex/regulex#57]
this cannot work 
`(?<!VD)AC`
![image](https://user-images.githubusercontent.com/17997918/187826350-c1a41549-69ce-4288-af0c-d171bc4b93db.png)

**Comment by DMKun** [comment]
112233

**Comment by DerDemystifier** [comment]
Refer to #16 

@liudongmiao has added support for lookbehinds, atomic groups, etc. Check his version at : https://jianyu.io/regulex/

**Comment by DMKun** [comment]
![image](https://github.com/CJex/regulex/assets/17997918/4f3c3ff3-f3bf-4b49-b9bf-bea6b3dbced2)
It's work!
